name: age_calculation
description: A Neumorphism Age Calculator app using GetX, MVC, responsive design, localization, and tests.
publish_to: "none"
version: 1.0.1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  share_plus: ^12.0.0
  screenshot: ^3.0.0
  flutter_neumorphic_plus: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.5.1
  build_runner: ^2.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #